<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Register extends CI_Controller {
	public function __construct()
    {
        parent::__construct();
        $this->load->helper(array('form','url','html'));
		$this->load->model('Modeladmin');
		include APPPATH . 'third_party/PersianCalendar.php';
		include APPPATH . 'third_party/KavenegarApi.php';
		$this->load->library('email');
	}

	public function register()
	{
		$firstname_en=$this->input->post('firstname_en');
		$lastname_en=$this->input->post('lastname_en');
		$firstname_fa=$this->input->post('firstname_fa');
		$lastname_fa=$this->input->post('lastname_fa');
		$mobile=$this->input->post('mobile');
		$email=$this->input->post('email');
		$comment=$this->input->post('comment');
		$date=date("Y-m-d");



		$moshavereh=array(
			"s_firstname_en"=>$firstname_en,
			"s_lastname_en"=>$lastname_en,
			"s_firstname_fa"=>$firstname_fa,
			"s_lastname_fa"=>$lastname_fa,
			"s_email"=>$email,
			"s_mobile"=>$mobile,
			"s_date"=>$date,
			"comment"=>"comment"
		);
		$res=$this->Modeladmin->register($moshavereh,$email);
		

		$data=[
			'receptor'=>"09123068775",
			'sender'=>'10001000990044',
			'message'=>"ثبت نام انجام شد"
		];
		
		if($res=="success"){
			$this->sendsms($data);
		}
		echo $res;

	}




	public function reg_users()
	{
	

		$firstname=$this->input->post('firstname');
		$lastname=$this->input->post('lastname');
		$fathername=$this->input->post('fathername');
		$sh_number=$this->input->post('sh_number');
		$national=$this->input->post('national');
		$bdate=$this->input->post('bdate');
		$mobile=$this->input->post('mobile');
		$job=$this->input->post('job');
		$email=$this->input->post('email');
		$password=$this->input->post('password');
		$major=$this->input->post('major');
		$marital=$this->input->post('marital');
		$education=$this->input->post('education');
		$depart=$this->input->post('depart');
		$period=$this->input->post('period');
		// print_r($_POST);die("ok");

		$date_en=date("Y-m-d");
		$date_fa=mds_date("Y/m/d", "now" );

		$reg_users=array(
			"first_name"=>$firstname,
			"last_name"=>$lastname,
			"father_name"=>$fathername,
			"sh_number"=>$sh_number,
			"natioanl_numbr"=>$national,
			"username"=>$national,
			"b_date"=>$bdate,
			"job"=>$job,
			"email"=>$email,
			"password"=>$password,
			"major"=>$major,
			"marride"=>$marital,
			"education"=>$education,
			"depart"=>$depart,
			"requested_course"=>$period,
			"date_en"=>$date_en,
			"date_fa"=>$date_fa,
			"mobile"=>$mobile,
		);
		$res=$this->Modeladmin->reg_users($reg_users,$national);
		
		$msg="کاربر: ".$firstname." ".$lastname." ثبت نام شد.";
		
		if($res=="insert"){
			$data=[
				'receptor'=>"09123068775",
				'sender'=>'10001000990044',
				'message'=>$msg
			];
			// $KavenegarApi =new KavenegarApi("59594A482B2F574C544E4F424B414279595041536E5268424B6A327179756C6E53546569726151554D6C413D" , false);
			// $sms=$KavenegarApi->Send("10001000990044", "09123068775", $msg, $date = null, $type = null, $localid = null);
			$this->sendsms($data);
			$this->sendEmail($firstname,$lastname,$email);
			echo "insert";
		}else if($res=="duplicate"){
			echo "duplicate";
		}else{
			echo "error";
		}

		

	}




	public function check_sms(){
		$otp_user=$this->input->post('otp');
		$otp=$usrlogin=$this->session->userdata['otp'];
		$mobile=$usrlogin=$this->session->userdata['mobile'];

		if($otp_user==$otp){
			echo "success";
		}else{
			echo "error";
		}
	}


	public function sent_code(){
		$mobile=$this->input->post('mobile');
		$otp=$this->n_digit_random(4);
		$otp=1234;
		$this->session->set_userdata('otp', $otp);
		$this->session->set_userdata('mobile', $mobile);
		$otp=$usrlogin=$this->session->userdata['otp'];
		
		$msg="به مرکز آموزش حدادیان خوش آمدید کد فعالسازی شما ".$otp." می باشد. <br/> با تشکر";

		$data=[
			'receptor'=>$mobile,
			'sender'=>'10001000990044',
			'message'=>$msg
		];
		
		// $this->sendsms($data);
		
		
		echo "success";
	}

	public function n_digit_random($digits) {
		$temp = "";
	  
		for ($i = 0; $i < $digits; $i++) {
		  $temp .= rand(0, 9);
		}
	  
		return (int)$temp;
	  }


	  function sendsms($data){

		$req=null;
		foreach ($data as $key => $value) {
			$value = urlencode($value);
			$req .= "&$key=$value";
		}


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'http://api.kavenegar.com/v1/59594A482B2F574C544E4F424B414279595041536E5268424B6A327179756C6E53546569726151554D6C413D/sms/Send.json');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $req);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
	  }



	  public function sendEmail($firstname,$lastname,$email){

		$message = "<html ><body style='font-family:Tahoma;' dir='rtl'>";
		$message .= "کاربر گرامی ،<h3 style='color:blue;'> $firstname $lastname </h3>";
		$message .= "<p> 
		به مرکز آموزش حدادیان خوش آمدید 
		با تشکر<br/>
		</p>";
		
		$message.= "</body></html>";
		// echo $message;die;
        $this->email->from('info@haddadiantc.com', 'مرکز آموزش حدادیان');
        $this->email->to($email);
        $this->email->subject('مرکز آموزش حدادیان');
        $this->email->message($message);
		$res=$this->email->send();
		return $res;
    }




}
